Set WEB_CONCURRENCY_SET_BY if appropriate
heroku/heroku-buildpack-nodejs pull request #932
Opened 2021-07-01 09:58 UTC by dzuelke

If `WEB_CONCURRENCY` is unset and we are calculating it, or if it is set to an out-of-bounds value, then we set `WEB_CONCURRENCY_SET_BY=heroku/nodejs`.

The purpose of this variable is to allow other buildpacks that run after this buildpack, but are actually the buildpack that's launching the web process, to be able to ignore the set value, or at least warn the user about the potentially wrong value for their purpose.

Without this, it's not possible for following code (e.g. the `WEB_CONCURRENCY` calculation of another language) to tell the whether `WEB_CONCURRENCY` was set by the user, or whether it was set by e.g. `heroku/nodejs` - the variable exists in the environment in either case.

It's not uncommon for users of other programming languages to use `heroku/nodejs` together with their language, and have it e.g. build assets with webpack. The correct usage order in that case of course is to have heroku/nodejs install webpack first, then have the "main" programming language buildpack run, and from in there, using whatever hooks it provides, run e.g. '`webpack`' - but many users instead set their "primary" language buildpack set as the first buildpack, and `heroku/nodejs` second (and have that run e.g. '`webpack`' for them during `npm install`).

2021-07-01 10:04 UTC, edmorley requested changes
Hi! Thank you for the PR.

I don't think this implementation will work, since this buildpack's `profile/WEB_CONCURRENCY.sh` will overwrite any older buildpack's `profile/WEB_CONCURRENCY.sh` at build time, so the "was `WEB_CONCURRENCY` already set by another buildpack" check won't work in the profile script at runtime.

I feel like this needs a decision record or similar first explaining the design choices, which we can discuss as a team --- since it has impact on other buildpacks. The current design was meant to solve the "which `WEB_CONCURRENCY` wins" issue (but I agree it doesn't in all cases). I'm keen to ensure the new solution doesn't have different issues of it's own.

2021-07-01 11:11 UTC, dzuelke commented
Apologies for the confusing description; I've improved the commit message.

Wish I could turn this back into a draft PR...

2022-03-01 17:44 UTC, dzuelke commented
> Apologies for the confusing description; I've improved the commit message.
> 
> Wish I could turn this back into a draft PR...

https://github.blog/changelog/2020-04-08-convert-pull-request-to-draft/

2023-10-31 14:38 UTC, colincasey commented
@dzuelke can we close this draft PR?

2023-11-24 16:16 UTC, closed without merging